sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create --yes -n env_name python=$PYTHON_VERSION --file conda-requirements.txt
  - source activate env_name
  - pip install -r pip-requirements.txt
  - pip install -e . --no-deps
script:
  - nosetests 
